import {
  PermissionModuleGroup,
  AppRole,
} from "../../models/Permission/permissionModel";

export const PERMISSION_MODULES: PermissionModuleGroup[] = [
  {
    moduleKey: "hardware",
    moduleName: "Quản lý Thiết bị phần cứng",
    icon: "💻",
    description: "Hồ sơ máy trạm, laptop, máy chủ, serial tag, bảo hành và kiểm kê kho",
    permissions: [
      {
        id: "hardware.view",
        code: "hardware.view",
        name: "Xem danh sách thiết bị",
        module: "Thiết bị phần cứng",
        moduleKey: "hardware",
        action: "VIEW",
        description: "Cho phép xem danh sách, thông số kỹ thuật và hồ sơ thiết bị",
      },
      {
        id: "hardware.create",
        code: "hardware.create",
        name: "Nhập kho thiết bị mới",
        module: "Thiết bị phần cứng",
        moduleKey: "hardware",
        action: "CREATE",
        description: "Cho phép tạo mới hồ sơ máy tính, gán barcode và nhập kho",
      },
      {
        id: "hardware.update",
        code: "hardware.update",
        name: "Cập nhật cấu hình & Cấp phát",
        module: "Thiết bị phần cứng",
        moduleKey: "hardware",
        action: "UPDATE",
        description: "Cho phép sửa thông số, điều chuyển phòng ban và bàn giao nhân viên",
      },
      {
        id: "hardware.delete",
        code: "hardware.delete",
        name: "Thanh lý & Xóa hồ sơ",
        module: "Thiết bị phần cứng",
        moduleKey: "hardware",
        action: "DELETE",
        description: "Cho phép thanh lý phế liệu và xóa thiết bị khỏi hệ thống",
      },
      {
        id: "hardware.export",
        code: "hardware.export",
        name: "Xuất dữ liệu & Biên bản",
        module: "Thiết bị phần cứng",
        moduleKey: "hardware",
        action: "EXPORT",
        description: "Cho phép xuất file Excel kiểm kê và in biên bản bàn giao",
      },
    ],
  },
  {
    moduleKey: "digital",
    moduleName: "Tài nguyên số & Bản quyền",
    icon: "🌐",
    description: "Quản lý cloud server, tên miền, chứng chỉ SSL, SaaS accounts",
    permissions: [
      {
        id: "digital.view",
        code: "digital.view",
        name: "Xem danh mục tài nguyên số",
        module: "Tài nguyên số",
        moduleKey: "digital",
        action: "VIEW",
        description: "Xem thông tin máy chủ đám mây, domain, SSL và bản quyền",
      },
      {
        id: "digital.create",
        code: "digital.create",
        name: "Đăng ký tài nguyên số mới",
        module: "Tài nguyên số",
        moduleKey: "digital",
        action: "CREATE",
        description: "Thêm mới máy chủ AWS/Azure, tên miền hoặc phần mềm",
      },
      {
        id: "digital.update",
        code: "digital.update",
        name: "Cập nhật & Gia hạn dịch vụ",
        module: "Tài nguyên số",
        moduleKey: "digital",
        action: "UPDATE",
        description: "Gia hạn SSL, nâng cấp cấu hình vCPU/RAM, đổi thông số",
      },
      {
        id: "digital.delete",
        code: "digital.delete",
        name: "Hủy bỏ tài nguyên số",
        module: "Tài nguyên số",
        moduleKey: "digital",
        action: "DELETE",
        description: "Hủy tên miền hết hạn hoặc đóng tài khoản SaaS",
      },
    ],
  },
  {
    moduleKey: "maintenance",
    moduleName: "Vận hành & Lịch bảo trì",
    icon: "🔧",
    description: "Kế hoạch bảo dưỡng định kỳ, sửa chữa sự cố và bảo hành thiết bị",
    permissions: [
      {
        id: "maintenance.view",
        code: "maintenance.view",
        name: "Xem lịch bảo trì",
        module: "Lịch bảo trì",
        moduleKey: "maintenance",
        action: "VIEW",
        description: "Xem kế hoạch bảo dưỡng trên lịch tháng, kanban và danh sách",
      },
      {
        id: "maintenance.create",
        code: "maintenance.create",
        name: "Lên lịch bảo trì mới",
        module: "Lịch bảo trì",
        moduleKey: "maintenance",
        action: "CREATE",
        description: "Khởi tạo công việc bảo trì, chọn thiết bị và phân công kỹ thuật",
      },
      {
        id: "maintenance.execute",
        code: "maintenance.execute",
        name: "Cập nhật tiến độ & Checklist",
        module: "Lịch bảo trì",
        moduleKey: "maintenance",
        action: "UPDATE",
        description: "Tích chọn các hạng mục checklist kỹ thuật và ghi nhận chi phí",
      },
      {
        id: "maintenance.approve",
        code: "maintenance.approve",
        name: "Nghiệm thu hoàn thành",
        module: "Lịch bảo trì",
        moduleKey: "maintenance",
        action: "APPROVE",
        description: "Ký duyệt nghiệm thu kỹ thuật và đóng phiếu bảo trì",
      },
    ],
  },
  {
    moduleKey: "monitoring",
    moduleName: "Giám sát Máy trạm (Telemetry)",
    icon: "📊",
    description: "Thu thập dữ liệu phần cứng thời gian thực từ Agent cài trên máy trạm",
    permissions: [
      {
        id: "monitoring.view",
        code: "monitoring.view",
        name: "Xem chỉ số giám sát",
        module: "Giám sát máy trạm",
        moduleKey: "monitoring",
        action: "VIEW",
        description: "Xem tải CPU, RAM, bản quyền Windows/Office các máy trạm",
      },
      {
        id: "monitoring.alert",
        code: "monitoring.alert",
        name: "Cấu hình cảnh báo quá tải",
        module: "Giám sát máy trạm",
        moduleKey: "monitoring",
        action: "UPDATE",
        description: "Cấu hình ngưỡng RAM > 90%, cảnh báo máy sắp hết hạn bản quyền",
      },
    ],
  },
  {
    moduleKey: "reports",
    moduleName: "Báo cáo & Thống kê Tài chính",
    icon: "📈",
    description: "Biểu đồ xu hướng chi phí Capex/Opex, cơ cấu danh mục và khấu hao",
    permissions: [
      {
        id: "reports.view",
        code: "reports.view",
        name: "Xem báo cáo thống kê",
        module: "Báo cáo & Thống kê",
        moduleKey: "reports",
        action: "VIEW",
        description: "Xem biểu đồ tài chính, tổng giá trị tài sản và xu hướng",
      },
      {
        id: "reports.export",
        code: "reports.export",
        name: "Xuất file báo cáo tài chính",
        module: "Báo cáo & Thống kê",
        moduleKey: "reports",
        action: "EXPORT",
        description: "Xuất dữ liệu báo cáo chi phí ra file Excel, PDF",
      },
    ],
  },
  {
    moduleKey: "users",
    moduleName: "Người dùng & Bảo mật hệ thống",
    icon: "👥",
    description: "Quản trị danh sách nhân viên, tài khoản đăng nhập và phân quyền RBAC",
    permissions: [
      {
        id: "users.view",
        code: "users.view",
        name: "Xem danh sách tài khoản",
        module: "Người dùng",
        moduleKey: "users",
        action: "VIEW",
        description: "Xem danh sách người dùng, chức vụ và phòng ban",
      },
      {
        id: "users.manage",
        code: "users.manage",
        name: "Quản trị tài khoản (CRUD)",
        module: "Người dùng",
        moduleKey: "users",
        action: "UPDATE",
        description: "Thêm mới, sửa thông tin, khóa tài khoản và reset mật khẩu",
      },
      {
        id: "users.roles",
        code: "users.roles",
        name: "Quản lý vai trò & Phân quyền",
        module: "Người dùng",
        moduleKey: "users",
        action: "UPDATE",
        description: "Tùy biến ma trận phân quyền và gán quyền cho các vai trò",
      },
    ],
  },
  {
    moduleKey: "audit",
    moduleName: "Nhật ký Hệ thống (Audit Trail)",
    icon: "📜",
    description: "Theo dõi toàn bộ lịch sử thao tác dữ liệu OldData/NewData chuẩn SOC 2",
    permissions: [
      {
        id: "audit.view",
        code: "audit.view",
        name: "Xem nhật ký kiểm toán",
        module: "Nhật ký hệ thống",
        moduleKey: "audit",
        action: "AUDIT",
        description: "Xem lịch sử thay đổi INSERT, UPDATE, DELETE và so sánh Diff",
      },
      {
        id: "audit.export",
        code: "audit.export",
        name: "Xuất nhật ký kiểm toán",
        module: "Nhật ký hệ thống",
        moduleKey: "audit",
        action: "EXPORT",
        description: "Xuất dữ liệu kiểm toán ra file CSV phục vụ thanh tra nội bộ",
      },
    ],
  },
];

// Lấy tất cả IDs quyền
export const ALL_PERMISSION_IDS: string[] = PERMISSION_MODULES.flatMap((m) =>
  m.permissions.map((p) => p.id)
);

export const INITIAL_APP_ROLES: AppRole[] = [
  {
    id: "role-superadmin",
    code: "SUPER_ADMIN",
    name: "Quản trị tối cao",
    description: "Toàn quyền cấu hình hệ thống, quản trị người dùng, phân quyền và kiểm toán",
    badgeClass: "bg-red-50 text-red-700 dark:bg-red-950/60 dark:text-red-300 border-red-200 dark:border-red-800",
    color: "#ef4444",
    isSystem: true,
    usersCount: 1,
    permissions: [...ALL_PERMISSION_IDS], // Đầy đủ toàn bộ quyền
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "role-assetmanager",
    code: "ASSET_MANAGER",
    name: "Quản lý Tài sản IT",
    description: "Quản lý vòng đời phần cứng, tài nguyên số, cấp phát, điều chuyển và thanh lý",
    badgeClass: "bg-indigo-50 text-indigo-700 dark:bg-indigo-950/60 dark:text-indigo-300 border-indigo-200 dark:border-indigo-800",
    color: "#6366f1",
    isSystem: true,
    usersCount: 2,
    permissions: [
      "hardware.view",
      "hardware.create",
      "hardware.update",
      "hardware.delete",
      "hardware.export",
      "digital.view",
      "digital.create",
      "digital.update",
      "digital.delete",
      "maintenance.view",
      "maintenance.create",
      "maintenance.execute",
      "maintenance.approve",
      "monitoring.view",
      "reports.view",
      "reports.export",
      "users.view",
      "audit.view",
    ],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-02-15T00:00:00Z",
  },
  {
    id: "role-itsupport",
    code: "IT_SUPPORT",
    name: "Kỹ thuật IT / Helpdesk",
    description: "Tiếp nhận bảo trì, sửa chữa phần cứng, đo kiểm thiết bị và hỗ trợ người dùng",
    badgeClass: "bg-cyan-50 text-cyan-700 dark:bg-cyan-950/60 dark:text-cyan-300 border-cyan-200 dark:border-cyan-800",
    color: "#06b6d4",
    isSystem: true,
    usersCount: 1,
    permissions: [
      "hardware.view",
      "hardware.update",
      "digital.view",
      "maintenance.view",
      "maintenance.create",
      "maintenance.execute",
      "monitoring.view",
      "monitoring.alert",
      "users.view",
    ],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "role-auditor",
    code: "AUDITOR",
    name: "Kiểm toán & Kế toán",
    description: "Đối soát tài sản, báo cáo chi phí, khấu hao và kiểm tra nhật ký thay đổi",
    badgeClass: "bg-purple-50 text-purple-700 dark:bg-purple-950/60 dark:text-purple-300 border-purple-200 dark:border-purple-800",
    color: "#a855f7",
    isSystem: true,
    usersCount: 1,
    permissions: [
      "hardware.view",
      "hardware.export",
      "digital.view",
      "maintenance.view",
      "reports.view",
      "reports.export",
      "users.view",
      "audit.view",
      "audit.export",
    ],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "role-depthead",
    code: "DEPT_HEAD",
    name: "Trưởng phòng ban",
    description: "Theo dõi tài sản phân bổ cho phòng ban và phê duyệt kế hoạch bảo trì",
    badgeClass: "bg-amber-50 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300 border-amber-200 dark:border-amber-800",
    color: "#f59e0b",
    isSystem: true,
    usersCount: 2,
    permissions: [
      "hardware.view",
      "digital.view",
      "maintenance.view",
      "reports.view",
      "users.view",
    ],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "role-staff",
    code: "STAFF",
    name: "Nhân viên thông thường",
    description: "Xem thông tin máy tính được cấp phát và yêu cầu sửa chữa cơ bản",
    badgeClass: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300 border-slate-200 dark:border-slate-700",
    color: "#64748b",
    isSystem: true,
    usersCount: 3,
    permissions: [
      "hardware.view",
      "maintenance.view",
    ],
    createdAt: "2023-01-01T00:00:00Z",
    updatedAt: "2023-01-01T00:00:00Z",
  },
];
