import { MaintenanceTask } from "../../models/Maintenance/maintenancePlan";

// Tạo ngày linh hoạt xung quanh thời điểm hiện tại
const now = new Date();

const getDateStr = (dayOffset: number): string => {
  const d = new Date(now.getTime() + dayOffset * 24 * 60 * 60 * 1000);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
};

export const INITIAL_MAINTENANCE_TASKS: MaintenanceTask[] = [
  {
    id: "mnt-task-001",
    planCode: "MNT-2026-0101",
    title: "Vệ sinh & tra keo tản nhiệt dàn máy trạm đồ họa Phòng Dev",
    type: "PREVENTIVE",
    status: "IN_PROGRESS",
    priority: "HIGH",
    assetId: "HW-PC-0021",
    assetCode: "HW-PC-0021",
    assetName: "Máy trạm thiết kế đồ họa & phát triển TUF Gaming",
    assetCategory: "Máy trạm để bàn (Workstation)",
    locationName: "Tòa nhà A - Tầng 4 (Phòng Dev)",
    departmentName: "Phòng Công nghệ & IT",
    startDate: getDateStr(-1),
    endDate: getDateStr(1),
    startTime: "09:00",
    endTime: "17:00",
    estimatedDurationHours: 8,
    assignedTo: "KTV Nguyễn Văn Hoàng",
    vendorName: "Đội Kỹ thuật IT Nội bộ AIMS",
    estimatedCost: 1500000,
    actualCost: 1200000,
    description: "Thực hiện vệ sinh thổi bụi case máy tính, tra lại keo gốm tản nhiệt Arctic MX-4 cho CPU Intel Core i7-12700 và GPU RTX 3060.",
    checklist: [
      { id: "c1", text: "Thổi sạch bụi lọc gió và quạt tản nhiệt case", completed: true },
      { id: "c2", text: "Lau sạch keo tản nhiệt cũ trên bề mặt CPU & GPU", completed: true },
      { id: "c3", text: "Tra keo tản nhiệt mới & lắp lại tản tháp", completed: true },
      { id: "c4", text: "Stress test kiểm tra nhiệt độ dưới 75°C bằng Cinebench", completed: false },
      { id: "c5", text: "Ký biên bản nghiệm thu với trưởng nhóm Dev", completed: false },
    ],
    notes: "Ưu tiên làm sau 17h hoặc cuối tuần để tránh gián đoạn tiến độ sprint.",
    createdAt: new Date(now.getTime() - 5 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mnt-task-002",
    planCode: "MNT-2026-0102",
    title: "Đo kiểm dung lượng pin & bảo dưỡng bộ lưu điện UPS APC 10kVA",
    type: "INSPECTION",
    status: "SCHEDULED",
    priority: "CRITICAL",
    assetId: "UPS-SRV-001",
    assetCode: "HW-UPS-0012",
    assetName: "Bộ lưu điện trung tâm APC Smart-UPS RT 10000VA",
    assetCategory: "Thiết bị mạng & Điện tử",
    locationName: "Phòng Máy chủ Trung tâm (Server Room Tầng 4)",
    departmentName: "Phòng Công nghệ & IT",
    startDate: getDateStr(2),
    endDate: getDateStr(2),
    startTime: "08:30",
    endTime: "11:30",
    estimatedDurationHours: 3,
    assignedTo: "KTV Trần Quang Đức",
    vendorName: "Trung tâm Dịch vụ Schneider Electric",
    estimatedCost: 4500000,
    actualCost: null,
    description: "Kiểm tra định kỳ 6 tháng điện áp bình ắc quy, trở kháng trong và mô phỏng cúp điện lưới chuyển mạch sang máy phát dự phòng.",
    checklist: [
      { id: "c1", text: "Đo điện áp từng khối acquy AGM 12V", completed: false },
      { id: "c2", text: "Kiểm tra hệ thống quạt tản nhiệt biến tần", completed: false },
      { id: "c3", text: "Mô phỏng mất điện lưới trong 10 phút kiểm tra độ xả", completed: false },
      { id: "c4", text: "Cập nhật firmware NMC3 Network Card", completed: false },
    ],
    notes: "Yêu cầu thông báo toàn công ty trước 24h về thời gian thử tải.",
    createdAt: new Date(now.getTime() - 4 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mnt-task-003",
    planCode: "MNT-2026-0103",
    title: "Thay panel màn hình Dell UltraSharp 27 inch bị sọc chỉ",
    type: "CORRECTIVE",
    status: "SCHEDULED",
    priority: "MEDIUM",
    assetId: "HW-MON-0042",
    assetCode: "HW-MON-0042",
    assetName: "Màn hình đồ họa Dell UltraSharp U2723QE 4K",
    assetCategory: "Màn hình hiển thị (Monitor)",
    locationName: "Tòa nhà A - Tầng 2 (Phòng Marketing)",
    departmentName: "Phòng Marketing & Truyền thông",
    startDate: getDateStr(3),
    endDate: getDateStr(4),
    startTime: "13:30",
    endTime: "16:00",
    estimatedDurationHours: 2.5,
    assignedTo: "KTV Lê Thùy Linh",
    vendorName: "Công ty TNHH Thiết bị Sao Mai",
    estimatedCost: 3200000,
    actualCost: null,
    description: "Màn hình có 1 đường sọc dọc màu tím giữa panel IPS, trung tâm bảo hành cử kỹ thuật viên đến thay cụm panel LCD mới tại chỗ.",
    checklist: [
      { id: "c1", text: "Tiếp nhận màn hình từ nhân viên Marketing", completed: false },
      { id: "c2", text: "Cấp phát màn hình dự phòng tạm thời cho nhân viên", completed: false },
      { id: "c3", text: "Kỹ thuật viên hãng thay thế panel màn hình mới", completed: false },
      { id: "c4", text: "Kiểm tra màu sắc, dead pixel và cổng Type-C 90W", completed: false },
    ],
    createdAt: new Date(now.getTime() - 3 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mnt-task-004",
    planCode: "MNT-2026-0104",
    title: "Nâng cấp dung lượng RAM 32GB lên 64GB cho Máy chủ Hyper-V",
    type: "UPGRADE",
    status: "COMPLETED",
    priority: "HIGH",
    assetId: "SRV-HVP-01",
    assetCode: "HW-SRV-0003",
    assetName: "Máy chủ ảo hóa Dell PowerEdge R650",
    assetCategory: "Máy chủ & Mạng",
    locationName: "Phòng Server Tầng 4 - Rack 02",
    departmentName: "Phòng Công nghệ & IT",
    startDate: getDateStr(-3),
    endDate: getDateStr(-3),
    startTime: "20:00",
    endTime: "22:30",
    estimatedDurationHours: 2.5,
    assignedTo: "KTV Trần Quang Đức",
    vendorName: "Công ty Cổ phần Tin học Phong Vũ",
    estimatedCost: 8500000,
    actualCost: 8200000,
    description: "Cắm thêm 2 thanh RAM DDR4 ECC 16GB Registered phục vụ mở rộng thêm 4 máy ảo chạy microservices Docker & CSDL Test.",
    checklist: [
      { id: "c1", text: "Sao lưu toàn bộ Snapshot các máy ảo", completed: true },
      { id: "c2", text: "Graceful shutdown Hyper-V Host", completed: true },
      { id: "c3", text: "Lắp đặt 2 thanh RAM ECC vào khe B1, B2", completed: true },
      { id: "c4", text: "Bật nguồn, kiểm tra iDRAC nhận diện đủ 64GB RAM", completed: true },
      { id: "c5", text: "Khởi động lại các VM và xác nhận dịch vụ trực tuyến", completed: true },
    ],
    completionReport: "Hoàn thành lúc 22:15, toàn bộ máy ảo hoạt động ổn định, RAM sử dụng hiện tại ở mức 54%.",
    createdAt: new Date(now.getTime() - 8 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 3 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mnt-task-005",
    planCode: "MNT-2026-0105",
    title: "Gửi trung tâm bảo hành Asus card đồ họa TUF RTX 3060 lỗi quạt",
    type: "WARRANTY",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    assetId: "HW-COMP-001",
    assetCode: "HW-PC-0033",
    assetName: "Linh kiện Card đồ họa ASUS TUF RTX 3060 12GB",
    assetCategory: "Linh kiện phần cứng",
    locationName: "Trung tâm Bảo hành Asus Việt Nam (Thái Hà)",
    departmentName: "Phòng Công nghệ & IT",
    startDate: getDateStr(-4),
    endDate: getDateStr(5),
    startTime: "10:00",
    endTime: "16:00",
    assignedTo: "KTV Nguyễn Văn Hoàng",
    vendorName: "Trung tâm Bảo hành Chính hãng Asus",
    estimatedCost: 0,
    actualCost: 0,
    description: "Quạt làm mát số 2 phát ra tiếng kêu kẹt bi và không quay khi tải nặng, thuộc diện bảo hành 36 tháng miễn phí của hãng.",
    checklist: [
      { id: "c1", text: "Tháo card đồ họa và đóng hộp chống sốc", completed: true },
      { id: "c2", text: "Lập phiếu bàn giao và gửi Asus Service Center", completed: true },
      { id: "c3", text: "Nhận phiếu hẹn trả ngày 05/10/2026", completed: true },
      { id: "c4", text: "Nhận lại card đã thay quạt và lắp lại máy", completed: false },
    ],
    notes: "Mã vận đơn gửi bảo hành: ASUS-RMA-884921.",
    createdAt: new Date(now.getTime() - 6 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 4 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mnt-task-006",
    planCode: "MNT-2026-0106",
    title: "Bảo dưỡng & tra dầu máy in laser mạng đa năng HP LaserJet",
    type: "PREVENTIVE",
    status: "COMPLETED",
    priority: "LOW",
    assetId: "HW-PRN-0012",
    assetCode: "HW-PRN-0012",
    assetName: "Máy in laser đa năng HP LaserJet Enterprise M507x",
    assetCategory: "Thiết bị ngoại vi (Printer)",
    locationName: "Tòa nhà A - Tầng 2 (Sảnh chung)",
    departmentName: "Phòng Hành chính - Nhân sự",
    startDate: getDateStr(-6),
    endDate: getDateStr(-6),
    startTime: "14:00",
    endTime: "16:30",
    estimatedDurationHours: 2.5,
    assignedTo: "KTV Lê Thùy Linh",
    vendorName: "Công ty Cổ phần Tin học Phong Vũ",
    estimatedCost: 650000,
    actualCost: 650000,
    description: "Lau sạch trục cuốn giấy cao su, hút mực thải thừa và tra dầu bôi trơn bánh răng cơ cấu kéo giấy.",
    checklist: [
      { id: "c1", text: "Vệ sinh gương scan và trục quang học", completed: true },
      { id: "c2", text: "Lau trục cao su nạp giấy khay 2 bằng cồn chuyên dụng", completed: true },
      { id: "c3", text: "In test 20 trang liên tục kiểm tra kẹt giấy", completed: true },
    ],
    completionReport: "Đã in thử 50 trang tài liệu HCNS, máy chạy êm, chất lượng bản in sắc nét.",
    createdAt: new Date(now.getTime() - 10 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 6 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mnt-task-007",
    planCode: "MNT-2026-0107",
    title: "Thay cụm sấy và bánh xe kéo giấy máy Photocopy Ricoh MP 5055",
    type: "CORRECTIVE",
    status: "OVERDUE",
    priority: "HIGH",
    assetId: "HW-COP-0001",
    assetCode: "HW-COP-0001",
    assetName: "Máy photocopy kỹ thuật số Ricoh Aficio MP 5055SP",
    assetCategory: "Thiết bị văn phòng",
    locationName: "Tòa nhà A - Tầng 3 (Phòng Kế toán)",
    departmentName: "Phòng Kế toán & Tài chính",
    startDate: getDateStr(-2),
    endDate: getDateStr(-1),
    startTime: "09:00",
    endTime: "12:00",
    estimatedDurationHours: 3,
    assignedTo: "KTV Nguyễn Văn Hoàng",
    vendorName: "Công ty Thiết bị Văn phòng Sao Mai",
    estimatedCost: 3800000,
    actualCost: null,
    description: "Máy in ra bản chụp bị vệt đen nhăn giấy do rách bao lụa cụm sấy. Đã quá hạn 2 ngày do linh kiện nhập về trễ.",
    checklist: [
      { id: "c1", text: "Tháo cụm sấy cũ bị rách bao lụa", completed: true },
      { id: "c2", text: "Lắp bao lụa mới chính hãng Ricoh và thoa mỡ chịu nhiệt", completed: false },
      { id: "c3", text: "Thay 3 quả đào cao su kéo giấy khay 1", completed: false },
      { id: "c4", text: "Kiểm tra chất lượng sao chụp và ký nghiệm thu", completed: false },
    ],
    notes: "CẢNH BÁO: Kế toán đang cần in chứng từ cuối tháng gấp, KTV khẩn trương liên hệ bên cung ứng linh kiện.",
    createdAt: new Date(now.getTime() - 4 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 1 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mnt-task-008",
    planCode: "MNT-2026-0108",
    title: "Bảo dưỡng hệ thống điều hòa chính xác phòng Server Stulz 20kW",
    type: "PREVENTIVE",
    status: "SCHEDULED",
    priority: "CRITICAL",
    assetId: "HW-AC-0001",
    assetCode: "HW-AC-0001",
    assetName: "Hệ thống điều hòa chính xác Stulz CyberAir 3 DX",
    assetCategory: "Hạ tầng Trung tâm dữ liệu",
    locationName: "Phòng Server Tầng 4",
    departmentName: "Phòng Công nghệ & IT",
    startDate: getDateStr(6),
    endDate: getDateStr(6),
    startTime: "08:00",
    endTime: "17:00",
    estimatedDurationHours: 8,
    assignedTo: "KTV Trần Quang Đức",
    vendorName: "Công ty Cổ phần Kỹ thuật Cơ điện REE",
    estimatedCost: 12000000,
    actualCost: null,
    description: "Bảo dưỡng định kỳ quý hệ thống máy lạnh chính xác: xịt rửa dàn ngưng ngoài trời, kiểm tra áp suất gas R410A, thay màng lọc bụi G4 và cân chỉnh độ ẩm 50%.",
    checklist: [
      { id: "c1", text: "Đo dòng tải máy nén inverter Copeland Scroll", completed: false },
      { id: "c2", text: "Đo áp suất hút / áp suất đẩy môi chất lạnh R410A", completed: false },
      { id: "c3", text: "Thay mới tấm lọc bụi lọc tinh G4 dàn lạnh", completed: false },
      { id: "c4", text: "Vệ sinh bình tạo ẩm hơi nước điện cực", completed: false },
    ],
    createdAt: new Date(now.getTime() - 2 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 2 * 24 * 3600 * 1000).toISOString(),
  },
  {
    id: "mnt-task-009",
    planCode: "MNT-2026-0109",
    title: "Kiểm tra định kỳ tem niêm phong & dán nhãn mã QR tài sản Tầng 1",
    type: "INSPECTION",
    status: "SCHEDULED",
    priority: "LOW",
    assetId: null,
    assetCode: "ALL-L1-ASSETS",
    assetName: "Toàn bộ tài sản cố định Sảnh lễ tân & Phòng họp Tầng 1",
    assetCategory: "Kiểm kê định kỳ",
    locationName: "Tòa nhà A - Tầng 1",
    departmentName: "Phòng Hành chính - Nhân sự",
    startDate: getDateStr(8),
    endDate: getDateStr(9),
    startTime: "09:00",
    endTime: "16:30",
    estimatedDurationHours: 12,
    assignedTo: "KTV Lê Thùy Linh",
    vendorName: "Tổ Kiểm kê Tài sản Doanh nghiệp",
    estimatedCost: 500000,
    actualCost: null,
    description: "Quét mã QR Code đối chiếu với phần mềm AIMS, in bổ sung tem vỡ và dán lại các tem bị bong tróc theo quy định kiểm kê quý.",
    checklist: [
      { id: "c1", text: "Kiểm kê 45 bộ bàn ghế và thiết bị họp trực tuyến", completed: false },
      { id: "c2", text: "In lại 12 tem mã vạch QR Code bị rách/mờ", completed: false },
      { id: "c3", text: "Đồng bộ trạng thái kiểm kê vào cơ sở dữ liệu AIMS", completed: false },
    ],
    createdAt: new Date(now.getTime() - 1 * 24 * 3600 * 1000).toISOString(),
    updatedAt: new Date(now.getTime() - 1 * 24 * 3600 * 1000).toISOString(),
  },
];
