import { UserAccount } from "../../models/User/userAccount";

export const INITIAL_USER_ACCOUNTS: UserAccount[] = [
  {
    id: 1,
    username: "admin.hoang",
    fullName: "Nguyễn Văn Hoàng",
    email: "hoang.it@aims.vn",
    phone: "0912.345.678",
    avatarUrl: null,
    departmentId: 1,
    departmentName: "Phòng Công nghệ & IT",
    positionId: 1,
    positionName: "Trưởng phòng IT / IT Director",
    roles: ["SuperAdmin", "AssetManager"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    lastLoginIp: "192.168.1.105",
    assignedAssets: [
      {
        assetId: "h1-0001",
        assetCode: "HW-PC-0021",
        assetName: "Máy trạm thiết kế đồ họa TUF Gaming Station",
        categoryName: "Máy trạm để bàn",
        assignedDate: "2023-08-18",
      },
      {
        assetId: "h1-0004",
        assetCode: "HW-MON-0042",
        assetName: "Màn hình đồ họa UltraSharp 27 inch 4K",
        categoryName: "Màn hình hiển thị",
        assignedDate: "2023-08-18",
      },
      {
        assetId: "d-ssl-001",
        assetCode: "DIG-KEY-001",
        assetName: "Khóa bảo mật phần cứng YubiKey 5 NFC Enterprise",
        categoryName: "Thiết bị bảo mật",
        assignedDate: "2024-01-10",
      },
    ],
    createdAt: "2023-01-15T08:00:00Z",
    updatedAt: "2024-03-20T10:30:00Z",
  },
  {
    id: 2,
    username: "linh.asset",
    fullName: "Lê Thùy Linh",
    email: "linh.asset@aims.vn",
    phone: "0988.765.432",
    avatarUrl: null,
    departmentId: 1,
    departmentName: "Phòng Công nghệ & IT",
    positionId: 2,
    positionName: "Chuyên viên Quản lý Tài sản IT",
    roles: ["AssetManager"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    lastLoginIp: "192.168.1.112",
    assignedAssets: [
      {
        assetId: "h1-0089",
        assetCode: "HW-LAP-0089",
        assetName: "Laptop MacBook Pro 16 inch M3 Max",
        categoryName: "Máy tính xách tay",
        assignedDate: "2024-02-15",
      },
      {
        assetId: "h1-0090",
        assetCode: "HW-PAD-0012",
        assetName: "Máy tính bảng iPad Pro 12.9 M2 kiểm kê kho",
        categoryName: "Thiết bị di động",
        assignedDate: "2024-02-15",
      },
    ],
    createdAt: "2023-03-10T09:00:00Z",
    updatedAt: "2024-02-15T14:00:00Z",
  },
  {
    id: 3,
    username: "duc.devops",
    fullName: "Trần Quang Đức",
    email: "duc.devops@aims.vn",
    phone: "0904.112.233",
    avatarUrl: null,
    departmentId: 1,
    departmentName: "Phòng Công nghệ & IT",
    positionId: 3,
    positionName: "Kỹ sư Trưởng Hạ tầng & DevOps",
    roles: ["ITSupport"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    lastLoginIp: "10.0.8.24",
    assignedAssets: [
      {
        assetId: "h1-0003",
        assetCode: "HW-LAP-0015",
        assetName: "Laptop doanh nhân ThinkPad T14 Gen 3",
        categoryName: "Máy tính xách tay",
        assignedDate: "2023-05-12",
      },
      {
        assetId: "d-srv-002",
        assetCode: "DIG-SRV-0002",
        assetName: "Máy chủ Cloud Production AWS API",
        categoryName: "Máy chủ đám mây",
        assignedDate: "2023-06-01",
      },
    ],
    createdAt: "2023-02-01T10:00:00Z",
    updatedAt: "2024-01-10T16:00:00Z",
  },
  {
    id: 4,
    username: "lan.hr",
    fullName: "Trần Thu Lan",
    email: "lan.hr@aims.vn",
    phone: "0977.889.900",
    avatarUrl: null,
    departmentId: 2,
    departmentName: "Phòng Hành chính - Nhân sự",
    positionId: 4,
    positionName: "Trưởng phòng Hành chính - Nhân sự",
    roles: ["DepartmentHead"],
    status: "ACTIVE",
    mfaEnabled: false,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    lastLoginIp: "192.168.1.88",
    assignedAssets: [
      {
        assetId: "h1-0002",
        assetCode: "HW-PC-0088",
        assetName: "Máy vi tính văn phòng OptiPlex 7000 Micro",
        categoryName: "Máy trạm để bàn",
        assignedDate: "2023-11-22",
      },
      {
        assetId: "h1-0050",
        assetCode: "HW-MON-0050",
        assetName: "Màn hình vi tính Dell 24 inch P2419H",
        categoryName: "Màn hình hiển thị",
        assignedDate: "2023-11-22",
      },
    ],
    createdAt: "2023-04-12T08:30:00Z",
    updatedAt: "2024-02-28T09:15:00Z",
  },
  {
    id: 5,
    username: "thao.ketoan",
    fullName: "Hoàng Phương Thảo",
    email: "thao.ketoan@aims.vn",
    phone: "0934.567.890",
    avatarUrl: null,
    departmentId: 3,
    departmentName: "Phòng Kế toán & Tài chính",
    positionId: 5,
    positionName: "Kế toán trưởng & Quản lý Chi phí",
    roles: ["Auditor"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
    lastLoginIp: "192.168.1.92",
    assignedAssets: [
      {
        assetId: "h1-0071",
        assetCode: "HW-PC-0071",
        assetName: "Máy tính kế toán HP ProDesk 400 G6",
        categoryName: "Máy trạm để bàn",
        assignedDate: "2023-09-01",
      },
      {
        assetId: "h1-0072",
        assetCode: "HW-PRN-0005",
        assetName: "Máy in laser Canon LBP 2900 in hóa đơn",
        categoryName: "Thiết bị ngoại vi",
        assignedDate: "2023-09-01",
      },
    ],
    createdAt: "2023-05-18T14:20:00Z",
    updatedAt: "2024-03-01T11:45:00Z",
  },
  {
    id: 6,
    username: "minh.ai",
    fullName: "TS. Nguyễn Công Minh",
    email: "minh.ai@aims.vn",
    phone: "0918.234.567",
    avatarUrl: null,
    departmentId: 4,
    departmentName: "Phòng Trí tuệ Nhân tạo (AI & Data)",
    positionId: 6,
    positionName: "Giám đốc Trung tâm AI & Nghiên cứu",
    roles: ["DepartmentHead", "AssetManager"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
    lastLoginIp: "192.168.1.135",
    assignedAssets: [
      {
        assetId: "h1-0105",
        assetCode: "HW-LAP-0105",
        assetName: "Mobile Workstation ThinkPad P1 Gen 5 RTX A4500",
        categoryName: "Máy tính xách tay",
        assignedDate: "2024-01-05",
      },
    ],
    createdAt: "2024-01-02T09:00:00Z",
    updatedAt: "2024-01-05T15:00:00Z",
  },
  {
    id: 7,
    username: "dung.sales",
    fullName: "Lê Quốc Dũng",
    email: "dung.sales@aims.vn",
    phone: "0945.678.901",
    avatarUrl: null,
    departmentId: 5,
    departmentName: "Phòng Kinh doanh & Tiếp thị",
    positionId: 7,
    positionName: "Trưởng nhóm Phát triển Khách hàng",
    roles: ["Staff"],
    status: "ACTIVE",
    mfaEnabled: false,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    lastLoginIp: "14.162.15.78",
    assignedAssets: [
      {
        assetId: "h1-0062",
        assetCode: "HW-LAP-0062",
        assetName: "Laptop Dell Vostro 5410 i5-11320H",
        categoryName: "Máy tính xách tay",
        assignedDate: "2023-07-20",
      },
    ],
    createdAt: "2023-07-15T11:00:00Z",
    updatedAt: "2023-07-20T16:30:00Z",
  },
  {
    id: 8,
    username: "mai.dev",
    fullName: "Vũ Tuyết Mai",
    email: "mai.dev@aims.vn",
    phone: "0963.221.445",
    avatarUrl: null,
    departmentId: 1,
    departmentName: "Phòng Công nghệ & IT",
    positionId: 8,
    positionName: "Kỹ sư Phần mềm Frontend",
    roles: ["Staff"],
    status: "ACTIVE",
    mfaEnabled: true,
    lastLoginAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    lastLoginIp: "192.168.1.144",
    assignedAssets: [
      {
        assetId: "h1-0077",
        assetCode: "HW-LAP-0077",
        assetName: "MacBook Air 15 inch M2 16GB",
        categoryName: "Máy tính xách tay",
        assignedDate: "2023-10-10",
      },
      {
        assetId: "h1-0078",
        assetCode: "HW-MON-0078",
        assetName: "Màn hình LG 27UP850 4K Type-C",
        categoryName: "Màn hình hiển thị",
        assignedDate: "2023-10-10",
      },
    ],
    createdAt: "2023-10-01T08:00:00Z",
    updatedAt: "2023-10-10T14:00:00Z",
  },
  {
    id: 9,
    username: "khang.intern",
    fullName: "Đỗ Tuấn Khang",
    email: "khang.intern@aims.vn",
    phone: "0923.456.789",
    avatarUrl: null,
    departmentId: 1,
    departmentName: "Phòng Công nghệ & IT",
    positionId: 9,
    positionName: "Thực tập sinh Quản trị Mạng",
    roles: ["Staff"],
    status: "PENDING",
    mfaEnabled: false,
    lastLoginAt: null,
    lastLoginIp: null,
    assignedAssets: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: 10,
    username: "nam.cu",
    fullName: "Nguyễn Hoài Nam",
    email: "nam.cu@aims.vn",
    phone: "0909.876.543",
    avatarUrl: null,
    departmentId: 5,
    departmentName: "Phòng Kinh doanh & Tiếp thị",
    positionId: 10,
    positionName: "Cựu nhân viên (Đã bàn giao)",
    roles: ["Staff"],
    status: "LOCKED",
    mfaEnabled: false,
    lastLoginAt: "2023-12-28T16:00:00Z",
    lastLoginIp: "113.190.234.12",
    assignedAssets: [],
    createdAt: "2023-02-15T09:00:00Z",
    updatedAt: "2023-12-31T17:00:00Z",
  },
];
