export const itResourceTypeList = [
  // ==================== DOMAIN / INTERNET ====================
  { value: "DOMAIN", label: "Tên miền (Domain)" },
  { value: "SUBDOMAIN", label: "Tên miền phụ (Subdomain)" },
  { value: "DNS", label: "DNS" },
  { value: "DNS_RECORD", label: "DNS Record" },
  { value: "PUBLIC_IP", label: "IP Public" },
  { value: "PRIVATE_IP", label: "IP Private" },
  { value: "ELASTIC_IP", label: "Elastic IP" },
  { value: "IP_RANGE", label: "Dải IP" },
  { value: "ASN", label: "ASN" },
  { value: "WHOIS", label: "WHOIS" },
  { value: "INTERNET_CONNECTION", label: "Đường truyền Internet" },
  { value: "BANDWIDTH", label: "Băng thông" },

  // ==================== SSL / CERTIFICATE ====================
  { value: "SSL_CERTIFICATE", label: "Chứng chỉ SSL/TLS" },
  { value: "WILDCARD_CERTIFICATE", label: "SSL Wildcard" },
  { value: "MULTI_DOMAIN_CERTIFICATE", label: "SSL Multi-Domain" },
  { value: "CODE_SIGNING_CERTIFICATE", label: "Chứng chỉ Code Signing" },
  { value: "CLIENT_CERTIFICATE", label: "Client Certificate" },
  { value: "ROOT_CERTIFICATE", label: "Root Certificate" },
  { value: "INTERMEDIATE_CERTIFICATE", label: "Intermediate Certificate" },

  // ==================== CLOUD ====================
  { value: "CLOUD_RESOURCE", label: "Tài nguyên Cloud" },
  { value: "CLOUD_ACCOUNT", label: "Tài khoản Cloud" },
  { value: "CLOUD_PROJECT", label: "Cloud Project" },
  { value: "CLOUD_SUBSCRIPTION", label: "Cloud Subscription" },
  { value: "CLOUD_INSTANCE", label: "Cloud Instance" },
  { value: "CLOUD_COMPUTE", label: "Cloud Compute" },
  { value: "CLOUD_FUNCTION", label: "Cloud Function" },
  { value: "SERVERLESS", label: "Serverless" },
  { value: "CLOUD_NETWORK", label: "Cloud Network" },
  { value: "CLOUD_VPC", label: "Cloud VPC" },
  { value: "CLOUD_LOAD_BALANCER", label: "Cloud Load Balancer" },
  { value: "CLOUD_STORAGE", label: "Cloud Storage" },
  { value: "CLOUD_DATABASE", label: "Cloud Database" },
  { value: "CLOUD_BACKUP", label: "Cloud Backup" },
  { value: "CLOUD_SECURITY", label: "Cloud Security" },
  { value: "CLOUD_SERVICE", label: "Dịch vụ Cloud" },
  { value: "CLOUD_ACCOUNT_CREDENTIAL", label: "Thông tin tài khoản Cloud" },

  // ==================== SERVER ====================
  { value: "PHYSICAL_SERVER", label: "Server vật lý" },
  { value: "VIRTUAL_MACHINE", label: "Máy chủ ảo (VM)" },
  { value: "VPS", label: "VPS" },
  { value: "DEDICATED_SERVER", label: "Dedicated Server" },
  { value: "BARE_METAL_SERVER", label: "Bare Metal Server" },
  { value: "RACK_SERVER", label: "Rack Server" },
  { value: "BLADE_SERVER", label: "Blade Server" },
  { value: "TOWER_SERVER", label: "Tower Server" },
  { value: "GPU_SERVER", label: "GPU Server" },
  { value: "APPLICATION_SERVER", label: "Application Server" },
  { value: "WEB_SERVER", label: "Web Server" },
  { value: "MAIL_SERVER", label: "Mail Server" },
  { value: "FILE_SERVER", label: "File Server" },
  { value: "PRINT_SERVER", label: "Print Server" },
  { value: "DNS_SERVER", label: "DNS Server" },
  { value: "DHCP_SERVER", label: "DHCP Server" },
  { value: "PROXY_SERVER", label: "Proxy Server" },
  { value: "BACKUP_SERVER", label: "Backup Server" },
  { value: "LOG_SERVER", label: "Log Server" },

  // ==================== NETWORK ====================
  { value: "ROUTER", label: "Router" },
  { value: "SWITCH", label: "Switch" },
  { value: "HUB", label: "Hub" },
  { value: "MANAGED_SWITCH", label: "Managed Switch" },
  { value: "UNMANAGED_SWITCH", label: "Unmanaged Switch" },
  { value: "LAYER_3_SWITCH", label: "Layer 3 Switch" },
  { value: "FIREWALL", label: "Firewall" },
  { value: "NEXT_GEN_FIREWALL", label: "Next-Generation Firewall" },
  { value: "LOAD_BALANCER", label: "Load Balancer" },
  { value: "GATEWAY", label: "Gateway" },
  { value: "MODEM", label: "Modem" },
  { value: "ACCESS_POINT", label: "Wi-Fi Access Point" },
  { value: "WIRELESS_CONTROLLER", label: "Wireless Controller" },
  { value: "NETWORK_CONTROLLER", label: "Network Controller" },
  { value: "NETWORK_BRIDGE", label: "Network Bridge" },
  { value: "REPEATER", label: "Repeater" },
  { value: "WIFI_EXTENDER", label: "Wi-Fi Extender" },
  { value: "MEDIA_CONVERTER", label: "Media Converter" },
  { value: "NETWORK_TAP", label: "Network TAP" },
  { value: "PROXY", label: "Proxy" },
  { value: "REVERSE_PROXY", label: "Reverse Proxy" },
  { value: "VPN", label: "VPN" },
  { value: "VPN_GATEWAY", label: "VPN Gateway" },
  { value: "SD_WAN", label: "SD-WAN" },
  { value: "NETWORK_APPLIANCE", label: "Network Appliance" },
  { value: "SFP_MODULE", label: "SFP Module" },
  { value: "NETWORK_CARD", label: "Network Card / NIC" },
  { value: "NETWORK_PORT", label: "Network Port" },

  // ==================== DATABASE ====================
  { value: "DATABASE", label: "Cơ sở dữ liệu" },
  { value: "DATABASE_SERVER", label: "Database Server" },
  { value: "RELATIONAL_DATABASE", label: "Relational Database" },
  { value: "NOSQL_DATABASE", label: "NoSQL Database" },
  { value: "DATABASE_CLUSTER", label: "Database Cluster" },
  { value: "DATABASE_REPLICA", label: "Database Replica" },
  { value: "DATABASE_INSTANCE", label: "Database Instance" },
  { value: "DATABASE_SCHEMA", label: "Database Schema" },
  { value: "DATABASE_BACKUP", label: "Database Backup" },
  { value: "CACHE", label: "Cache" },
  { value: "REDIS", label: "Redis" },
  { value: "ELASTICSEARCH", label: "Elasticsearch" },
  { value: "MONGODB", label: "MongoDB" },
  { value: "MYSQL", label: "MySQL" },
  { value: "POSTGRESQL", label: "PostgreSQL" },
  { value: "SQL_SERVER", label: "Microsoft SQL Server" },
  { value: "ORACLE_DATABASE", label: "Oracle Database" },

  // ==================== STORAGE ====================
  { value: "STORAGE", label: "Storage / Lưu trữ" },
  { value: "NAS", label: "NAS" },
  { value: "SAN", label: "SAN" },
  { value: "DAS", label: "DAS" },
  { value: "OBJECT_STORAGE", label: "Object Storage" },
  { value: "BLOCK_STORAGE", label: "Block Storage" },
  { value: "FILE_STORAGE", label: "File Storage" },
  { value: "STORAGE_VOLUME", label: "Storage Volume" },
  { value: "STORAGE_BUCKET", label: "Storage Bucket" },
  { value: "SNAPSHOT", label: "Snapshot" },
  { value: "ARCHIVE", label: "Archive" },

  // ==================== BACKUP / DR ====================
  { value: "BACKUP", label: "Backup" },
  { value: "BACKUP_POLICY", label: "Backup Policy" },
  { value: "BACKUP_JOB", label: "Backup Job" },
  { value: "BACKUP_STORAGE", label: "Backup Storage" },
  { value: "SNAPSHOT_BACKUP", label: "Snapshot Backup" },
  { value: "OFFSITE_BACKUP", label: "Offsite Backup" },
  { value: "DISASTER_RECOVERY", label: "Disaster Recovery" },
  { value: "DR_SITE", label: "DR Site" },
  { value: "REPLICATION", label: "Replication" },
  { value: "FAILOVER", label: "Failover" },

  // ==================== APPLICATION ====================
  { value: "APPLICATION", label: "Ứng dụng" },
  { value: "WEB_APPLICATION", label: "Web Application" },
  { value: "MOBILE_APPLICATION", label: "Mobile Application" },
  { value: "DESKTOP_APPLICATION", label: "Desktop Application" },
  { value: "APPLICATION_SERVER", label: "Application Server" },
  { value: "WEB_SERVICE", label: "Web Service" },
  { value: "API", label: "API" },
  { value: "API_SERVICE", label: "API Service" },
  { value: "MICROSERVICE", label: "Microservice" },
  { value: "IT_SERVICE", label: "IT Service" },
  { value: "BACKGROUND_SERVICE", label: "Background Service" },
  { value: "SCHEDULED_JOB", label: "Scheduled Job / Cron Job" },
  { value: "WEBHOOK", label: "Webhook" },
  { value: "WEBSITE", label: "Website" },
  { value: "PORTAL", label: "Portal" },
  { value: "CMS", label: "CMS" },
  { value: "ECOMMERCE", label: "E-Commerce" },

  // ==================== DEVOPS / CONTAINER ====================
  { value: "CONTAINER", label: "Container" },
  { value: "DOCKER", label: "Docker" },
  { value: "KUBERNETES", label: "Kubernetes" },
  { value: "KUBERNETES_CLUSTER", label: "Kubernetes Cluster" },
  { value: "KUBERNETES_NAMESPACE", label: "Kubernetes Namespace" },
  { value: "POD", label: "Kubernetes Pod" },
  { value: "CONTAINER_REGISTRY", label: "Container Registry" },
  { value: "HELM", label: "Helm Chart" },
  { value: "REPOSITORY", label: "Repository" },
  { value: "GIT_REPOSITORY", label: "Git Repository" },
  { value: "CODE_REPOSITORY", label: "Code Repository" },
  { value: "CI_CD", label: "CI/CD Pipeline" },
  { value: "BUILD_SERVER", label: "Build Server" },
  { value: "BUILD_ARTIFACT", label: "Build Artifact" },
  { value: "PACKAGE_REGISTRY", label: "Package Registry" },
  { value: "DEPLOYMENT", label: "Deployment" },
  { value: "RELEASE", label: "Release" },

  // ==================== SOFTWARE ====================
  { value: "SOFTWARE", label: "Phần mềm" },
  { value: "OPERATING_SYSTEM", label: "Hệ điều hành" },
  { value: "MIDDLEWARE", label: "Middleware" },
  { value: "RUNTIME", label: "Runtime" },
  { value: "FRAMEWORK", label: "Framework" },
  { value: "LIBRARY", label: "Library" },
  { value: "DRIVER", label: "Driver" },
  { value: "SOFTWARE_LICENSE", label: "Bản quyền phần mềm" },
  { value: "LICENSE_KEY", label: "License Key" },
  { value: "SUBSCRIPTION", label: "Software Subscription" },
  { value: "OPEN_SOURCE", label: "Open Source Software" },
  { value: "COMMERCIAL_SOFTWARE", label: "Commercial Software" },

  // ==================== SAAS / ONLINE SERVICES ====================
  { value: "SAAS", label: "SaaS" },
  { value: "PAAS", label: "PaaS" },
  { value: "IAAS", label: "IaaS" },
  { value: "AI_SERVICE", label: "Dịch vụ AI" },
  { value: "AI_API", label: "AI API" },
  { value: "CHAT_API", label: "Chat API" },
  { value: "LLM_API", label: "LLM API" },
  { value: "EMAIL_SERVICE", label: "Dịch vụ Email" },
  { value: "SMS_SERVICE", label: "Dịch vụ SMS" },
  { value: "PAYMENT_SERVICE", label: "Dịch vụ thanh toán" },
  { value: "ANALYTICS_SERVICE", label: "Dịch vụ Analytics" },
  { value: "SEARCH_SERVICE", label: "Dịch vụ Search" },
  { value: "MAP_SERVICE", label: "Dịch vụ bản đồ" },
  { value: "NOTIFICATION_SERVICE", label: "Dịch vụ Notification" },
  { value: "AUTHENTICATION_SERVICE", label: "Dịch vụ Authentication" },
  { value: "COLLABORATION_SERVICE", label: "Dịch vụ cộng tác" },
  { value: "DOCUMENT_SERVICE", label: "Dịch vụ tài liệu" },
  { value: "STORAGE_SERVICE", label: "Dịch vụ lưu trữ" },
  { value: "CDN_SERVICE", label: "Dịch vụ CDN" },

  // ==================== EMAIL / COLLABORATION ====================
  { value: "EMAIL", label: "Email" },
  { value: "EMAIL_ACCOUNT", label: "Tài khoản Email" },
  { value: "EMAIL_DOMAIN", label: "Email Domain" },
  { value: "MAILBOX", label: "Mailbox" },
  { value: "MAIL_SERVER", label: "Mail Server" },
  { value: "SMTP_SERVICE", label: "SMTP Service" },
  { value: "EMAIL_FORWARDING", label: "Email Forwarding" },
  { value: "CHAT_PLATFORM", label: "Chat / Messaging" },
  { value: "VIDEO_CONFERENCE", label: "Video Conference" },
  { value: "COLLABORATION_TOOL", label: "Công cụ cộng tác" },
  { value: "DOCUMENT_PLATFORM", label: "Nền tảng tài liệu" },

  // ==================== SECURITY ====================
  { value: "WAF", label: "Web Application Firewall" },
  { value: "DDOS_PROTECTION", label: "DDoS Protection" },
  { value: "ANTIVIRUS", label: "Antivirus" },
  { value: "ENDPOINT_SECURITY", label: "Endpoint Security" },
  { value: "EDR", label: "EDR" },
  { value: "XDR", label: "XDR" },
  { value: "SIEM", label: "SIEM" },
  { value: "IDS", label: "IDS" },
  { value: "IPS", label: "IPS" },
  { value: "VULNERABILITY_SCANNER", label: "Vulnerability Scanner" },
  { value: "PENETRATION_TEST", label: "Penetration Test" },
  { value: "SECURITY_POLICY", label: "Security Policy" },
  { value: "SECURITY_RULE", label: "Security Rule" },
  { value: "SECURITY_GROUP", label: "Security Group" },
  { value: "ACCESS_CONTROL", label: "Access Control" },
  { value: "MFA", label: "MFA / 2FA" },
  { value: "SSO", label: "Single Sign-On (SSO)" },
  { value: "ZERO_TRUST", label: "Zero Trust" },

  // ==================== IDENTITY / ACCESS ====================
  { value: "USER_ACCOUNT", label: "Tài khoản người dùng" },
  { value: "SERVICE_ACCOUNT", label: "Tài khoản dịch vụ" },
  { value: "ADMIN_ACCOUNT", label: "Tài khoản quản trị" },
  { value: "IAM", label: "IAM" },
  { value: "IAM_USER", label: "IAM User" },
  { value: "IAM_GROUP", label: "IAM Group" },
  { value: "IAM_ROLE", label: "IAM Role" },
  { value: "IAM_POLICY", label: "IAM Policy" },
  { value: "ROLE", label: "Role / Quyền truy cập" },
  { value: "PERMISSION", label: "Permission" },
  { value: "ACCESS_CONTROL_LIST", label: "Access Control List (ACL)" },
  { value: "CREDENTIAL", label: "Thông tin xác thực" },
  { value: "PASSWORD", label: "Mật khẩu" },
  { value: "SECRET", label: "Secret" },
  { value: "API_KEY", label: "API Key" },
  { value: "ACCESS_TOKEN", label: "Access Token" },
  { value: "REFRESH_TOKEN", label: "Refresh Token" },
  { value: "SSH_KEY", label: "SSH Key" },
  { value: "GPG_KEY", label: "GPG Key" },
  { value: "OAUTH_CLIENT", label: "OAuth Client" },

  // ==================== MONITORING / LOGGING ====================
  { value: "MONITORING", label: "Monitoring" },
  { value: "LOGGING", label: "Logging" },
  { value: "LOG_SERVER", label: "Log Server" },
  { value: "METRICS", label: "Metrics" },
  { value: "ALERTING", label: "Alerting" },
  { value: "APM", label: "Application Performance Monitoring" },
  { value: "TRACING", label: "Distributed Tracing" },
  { value: "DASHBOARD", label: "Dashboard" },
  { value: "UPTIME_MONITOR", label: "Uptime Monitor" },
  { value: "HEALTH_CHECK", label: "Health Check" },
  { value: "SYNTHETIC_MONITORING", label: "Synthetic Monitoring" },

  // ==================== HARDWARE ====================
  { value: "DESKTOP", label: "Máy tính để bàn" },
  { value: "LAPTOP", label: "Laptop" },
  { value: "WORKSTATION", label: "Workstation" },
  { value: "THIN_CLIENT", label: "Thin Client" },
  { value: "SMARTPHONE", label: "Smartphone" },
  { value: "TABLET", label: "Tablet" },
  { value: "SERVER_HARDWARE", label: "Phần cứng Server" },
  { value: "GPU", label: "GPU" },
  { value: "CPU", label: "CPU" },
  { value: "RAM", label: "RAM" },
  { value: "HARD_DISK", label: "Ổ cứng" },
  { value: "SSD", label: "SSD" },
  { value: "NETWORK_CARD", label: "Card mạng" },

  // ==================== PERIPHERAL ====================
  { value: "MONITOR", label: "Màn hình" },
  { value: "PRINTER", label: "Máy in" },
  { value: "SCANNER", label: "Máy scan" },
  { value: "PROJECTOR", label: "Máy chiếu" },
  { value: "WEBCAM", label: "Webcam" },
  { value: "KEYBOARD", label: "Bàn phím" },
  { value: "MOUSE", label: "Chuột" },
  { value: "HEADSET", label: "Tai nghe" },
  { value: "DOCKING_STATION", label: "Docking Station" },
  { value: "USB_DEVICE", label: "USB Device" },
  { value: "EXTERNAL_STORAGE", label: "Ổ lưu trữ ngoài" },

  // ==================== DATA CENTER ====================
  { value: "DATA_CENTER", label: "Data Center" },
  { value: "SERVER_RACK", label: "Tủ Rack" },
  { value: "RACK_UNIT", label: "Rack Unit (U)" },
  { value: "PDU", label: "PDU" },
  { value: "UPS", label: "UPS" },
  { value: "KVM_SWITCH", label: "KVM Switch" },
  { value: "KVM_CONSOLE", label: "KVM Console" },
  { value: "POWER_DISTRIBUTION", label: "Hệ thống phân phối điện" },
  { value: "COOLING_SYSTEM", label: "Hệ thống làm mát" },
  { value: "COLOCATION", label: "Colocation" },

  // ==================== IOT / SECURITY DEVICE ====================
  { value: "IOT_DEVICE", label: "Thiết bị IoT" },
  { value: "IP_CAMERA", label: "Camera IP" },
  { value: "NVR", label: "NVR" },
  { value: "DVR", label: "DVR" },
  { value: "BIOMETRIC_DEVICE", label: "Thiết bị sinh trắc học" },
  { value: "ACCESS_CONTROL_DEVICE", label: "Thiết bị kiểm soát ra vào" },
  { value: "SMART_SENSOR", label: "Smart Sensor" },
  { value: "IOT_GATEWAY", label: "IoT Gateway" },

  // ==================== HOSTING / CDN ====================
  { value: "HOSTING", label: "Hosting" },
  { value: "WEB_HOSTING", label: "Web Hosting" },
  { value: "MANAGED_HOSTING", label: "Managed Hosting" },
  { value: "CDN", label: "CDN" },
  { value: "EDGE_SERVICE", label: "Edge Service" },
  { value: "DOMAIN_REGISTRAR", label: "Domain Registrar" },
  { value: "DNS_PROVIDER", label: "DNS Provider" },
  { value: "CLOUD_PROVIDER", label: "Cloud Provider" },
  { value: "DATA_CENTER_PROVIDER", label: "Data Center Provider" },

  // ==================== DEV / PROJECT ====================
  { value: "PROJECT", label: "Project" },
  { value: "ENVIRONMENT", label: "Environment" },
  { value: "DEVELOPMENT_ENVIRONMENT", label: "Development Environment" },
  { value: "TEST_ENVIRONMENT", label: "Test Environment" },
  { value: "STAGING_ENVIRONMENT", label: "Staging Environment" },
  { value: "PRODUCTION_ENVIRONMENT", label: "Production Environment" },
  { value: "DEVELOPMENT_SERVER", label: "Development Server" },
  { value: "TEST_SERVER", label: "Test Server" },
  { value: "STAGING_SERVER", label: "Staging Server" },
  { value: "PRODUCTION_SERVER", label: "Production Server" },
  { value: "VERSION", label: "Version" },
  { value: "RELEASE", label: "Release" },
  { value: "DEPLOYMENT", label: "Deployment" },
  { value: "CONFIGURATION", label: "Configuration" },

  // ==================== DOCUMENT / KNOWLEDGE ====================
  { value: "TECHNICAL_DOCUMENT", label: "Tài liệu kỹ thuật" },
  { value: "SYSTEM_DOCUMENT", label: "Tài liệu hệ thống" },
  { value: "ARCHITECTURE_DOCUMENT", label: "Tài liệu kiến trúc" },
  { value: "API_DOCUMENTATION", label: "Tài liệu API" },
  { value: "RUNBOOK", label: "Runbook" },
  { value: "KNOWLEDGE_BASE", label: "Knowledge Base" },
  { value: "STANDARD_OPERATING_PROCEDURE", label: "SOP" },
  { value: "CONFIGURATION_DOCUMENT", label: "Tài liệu cấu hình" },

  // ==================== VENDOR / CONTRACT ====================
  { value: "VENDOR", label: "Nhà cung cấp CNTT" },
  { value: "IT_VENDOR", label: "Nhà cung cấp dịch vụ CNTT" },
  { value: "IT_CONTRACT", label: "Hợp đồng CNTT" },
  { value: "SERVICE_CONTRACT", label: "Hợp đồng dịch vụ" },
  { value: "SUPPORT_CONTRACT", label: "Hợp đồng hỗ trợ" },
  { value: "MAINTENANCE_CONTRACT", label: "Hợp đồng bảo trì" },
  { value: "WARRANTY", label: "Bảo hành" },
  { value: "SUPPORT_SERVICE", label: "Dịch vụ hỗ trợ" },
  { value: "MAINTENANCE", label: "Bảo trì" },
  { value: "IT_SERVICE_PROVIDER", label: "Nhà cung cấp dịch vụ IT" },

  // ==================== OTHER ====================
  { value: "OTHER", label: "Khác" },
];