import { WorkstationMonitoring } from "../../models/Monitoring/workstationMonitoring";

export const INITIAL_WORKSTATIONS: WorkstationMonitoring[] = [
  {
    id: "e1a90c54-46c7-4632-9c16-2bc5566f1001",
    assetId: "IT-PC-0021",
    collectedAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(), // 12 phút trước
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 30).toISOString(),
    hostName: "DESKTOP-IT-HOANG",
    userName: "hoang.it",
    domainOrWorkgroup: "CORP.AIMS.VN",
    osName: "Windows 11 Pro 64-bit",
    osBuildNumber: 22631,
    osLicenseStatus: "Licensed",
    osLicenseType: "OEM:DM",
    osPartialProductKey: "3V66T",
    osOemKeyInBios: "NKJFK-GHP2W-D8269-XXXXX-3V66T",
    officeProductName: "Microsoft 365 Apps for enterprise",
    officeLicenseStatus: "Licensed",
    officeLicenseType: "Subscription",
    officePartialProductKey: "HFT79",
    mbManufacturer: "ASUSTeK COMPUTER INC.",
    mbProduct: "TUF GAMING B660M-PLUS WIFI",
    mbSerialNumber: "220501838400192",
    mbBiosVersion: "1620 (08/12/2023)",
    cpuName: "12th Gen Intel(R) Core(TM) i7-12700",
    cpuCores: 12,
    cpuLogicals: 20,
    cpuMaxClockSpeedMHz: 4900,
    ramTotalGB: 32.0,
    ramUsedGB: 19.2,
    ramFreeGB: 12.8,
    ramUsagePercent: 60.0,
  },
  {
    id: "b452e89d-21df-4fc3-b714-f463c2398002",
    assetId: "IT-PC-0088",
    collectedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(), // 45 phút trước
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 15).toISOString(),
    hostName: "DESKTOP-HR-LAN",
    userName: "lan.hr",
    domainOrWorkgroup: "CORP.AIMS.VN",
    osName: "Windows 11 Pro 64-bit",
    osBuildNumber: 22631,
    osLicenseStatus: "Licensed",
    osLicenseType: "Retail",
    osPartialProductKey: "8HVX7",
    osOemKeyInBios: "F3B8G-72NPQ-XXXXX-XXXXX-8HVX7",
    officeProductName: "Microsoft Office Home and Business 2021",
    officeLicenseStatus: "Licensed",
    officeLicenseType: "Retail",
    officePartialProductKey: "2K4MT",
    mbManufacturer: "Dell Inc.",
    mbProduct: "OptiPlex 7000 Micro",
    mbSerialNumber: "9FC4KL3",
    mbBiosVersion: "1.18.0",
    cpuName: "12th Gen Intel(R) Core(TM) i5-12500",
    cpuCores: 6,
    cpuLogicals: 12,
    cpuMaxClockSpeedMHz: 4600,
    ramTotalGB: 16.0,
    ramUsedGB: 9.6,
    ramFreeGB: 6.4,
    ramUsagePercent: 60.0,
  },
  {
    id: "f3c2b1a0-9876-4321-abcd-ef0123456003",
    assetId: null, // Chưa map tài sản
    collectedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), // 2 giờ trước
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    hostName: "DESKTOP-ACC-THAO",
    userName: "thao.ketoan",
    domainOrWorkgroup: "WORKGROUP",
    osName: "Windows 10 Pro 64-bit",
    osBuildNumber: 19045,
    osLicenseStatus: "Notification", // Cảnh báo bản quyền
    osLicenseType: "Volume:MAK",
    osPartialProductKey: "T83GX",
    osOemKeyInBios: "",
    officeProductName: "Microsoft Office Professional Plus 2019",
    officeLicenseStatus: "Unlicensed", // Office chưa kích hoạt
    officeLicenseType: "Volume:KMS",
    officePartialProductKey: "WFG78",
    mbManufacturer: "HP Inc.",
    mbProduct: "HP ProDesk 400 G6 MT",
    mbSerialNumber: "CNU12048X9",
    mbBiosVersion: "F.24",
    cpuName: "Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz",
    cpuCores: 6,
    cpuLogicals: 12,
    cpuMaxClockSpeedMHz: 4500,
    ramTotalGB: 8.0,
    ramUsedGB: 7.3,
    ramFreeGB: 0.7,
    ramUsagePercent: 91.25, // Cảnh báo tràn RAM
  },
  {
    id: "a7d8c9e0-1234-5678-90ab-cdef12345004",
    assetId: "IT-LAP-0015",
    collectedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), // 5 giờ trước
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 60).toISOString(),
    hostName: "LAPTOP-DEV-QUAN",
    userName: "quan.dev",
    domainOrWorkgroup: "CORP.AIMS.VN",
    osName: "Windows 11 Pro 64-bit",
    osBuildNumber: 26100,
    osLicenseStatus: "Licensed",
    osLicenseType: "OEM:DM",
    osPartialProductKey: "4Q8W2",
    osOemKeyInBios: "XXXXX-XXXXX-XXXXX-XXXXX-4Q8W2",
    officeProductName: "Microsoft 365 Apps for enterprise",
    officeLicenseStatus: "Licensed",
    officeLicenseType: "Subscription",
    officePartialProductKey: "HFT79",
    mbManufacturer: "Lenovo",
    mbProduct: "ThinkPad T14 Gen 3",
    mbSerialNumber: "PF3G9K12",
    mbBiosVersion: "N3MET09W (1.09)",
    cpuName: "AMD Ryzen 7 PRO 6850U with Radeon Graphics",
    cpuCores: 8,
    cpuLogicals: 16,
    cpuMaxClockSpeedMHz: 4700,
    ramTotalGB: 32.0,
    ramUsedGB: 22.4,
    ramFreeGB: 9.6,
    ramUsagePercent: 70.0,
  },
  {
    id: "99e8d7c6-b5a4-3210-9876-fedcba987005",
    assetId: null, // Chưa map tài sản
    collectedAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(), // 10 ngày trước (Mất kết nối)
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 90).toISOString(),
    hostName: "PC-KHO-HAI",
    userName: "hai.kho",
    domainOrWorkgroup: "WORKGROUP",
    osName: "Windows 10 Enterprise LTSC 2021",
    osBuildNumber: 19044,
    osLicenseStatus: "Licensed",
    osLicenseType: "Volume:MAK",
    osPartialProductKey: "C82P4",
    osOemKeyInBios: "",
    officeProductName: "Microsoft Office Standard 2016",
    officeLicenseStatus: "Licensed",
    officeLicenseType: "Volume:MAK",
    officePartialProductKey: "R88XY",
    mbManufacturer: "Gigabyte Technology Co., Ltd.",
    mbProduct: "H410M H",
    mbSerialNumber: "SN210250014298",
    mbBiosVersion: "F6",
    cpuName: "Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz",
    cpuCores: 4,
    cpuLogicals: 8,
    cpuMaxClockSpeedMHz: 4300,
    ramTotalGB: 8.0,
    ramUsedGB: 4.8,
    ramFreeGB: 3.2,
    ramUsagePercent: 60.0,
  },
];
